server:
  port: ${SERVER_PORT:9089}

spring:
  application:
    name: Spring-Outbox-Design-Pattern
  config:
    import: classpath:kafka_info.yml
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/outbox}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  sql:
    init:
      platform: postgres
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        delivery.timeout.ms: 120000
        retry.backoff.ms: 1000
logging:
  level:
    liquibase: INFO